// Mock data based on Unit model from models.py[file:1]
export const mockUnits = [
  {
    unitcode: 'A1-101',
    city: 'New Cairo',
    project: 'Sun Capital',
    status: 'Available',
    plottype: 'Apartment',
    buildingtype: 'Tower A',
    unittype: '2BR',
    numbedrooms: '2',
    numbathrooms: 2,
    numparkingslots: 1,
    netarea: 120.5,
    sellablearea: 140.2,
    baseprice: 3500000,
    cashprice: 3200000,
    maintenancepercent: 2.5,
    maintenancevalue: 8750,
    gas: 5000,
    parkingprice: 150000,
    finalprice: 3500000,
    discount: 0,
    unitmodel: 'A1',
    mirror: '',
    buildingnumber: 'A1',
    floor: '1',
    finishingspecs: 'Semi-Finished',
    internalarea: 110.5,
    coveredterraces: 10,
    uncoveredterraces: 20,
    bua: 140.2,
    psm: 25000,
    mainview: 'Garden',
    levels: 'Single',
    customer: '',
    broker: '',
    creationdate: '2025-01-15'
  },
  {
    unitcode: 'A1-102',
    city: 'New Cairo',
    project: 'Sun Capital',
    status: 'Reserved',
    plottype: 'Apartment',
    buildingtype: 'Tower A',
    unittype: '3BR',
    numbedrooms: '3',
    numbathrooms: 3,
    numparkingslots: 2,
    netarea: 160.8,
    sellablearea: 185.4,
    baseprice: 4800000,
    cashprice: 4400000,
    maintenancepercent: 2.5,
    maintenancevalue: 12000,
    gas: 6500,
    parkingprice: 300000,
    finalprice: 4750000,
    discount: 50000,
    unitmodel: 'A1',
    mirror: 'Mirror',
    buildingnumber: 'A1',
    floor: '1',
    finishingspecs: 'Fully Finished',
    internalarea: 145.8,
    coveredterraces: 15,
    uncoveredterraces: 25,
    bua: 185.4,
    psm: 25600,
    mainview: 'Pool',
    levels: 'Duplex',
    customer: 'Ahmed Ali',
    broker: 'Sales Team 1',
    creationdate: '2025-02-01'
  },
  {
    unitcode: 'B1-201',
    city: 'New Cairo',
    project: 'Sun Capital',
    status: 'Sold',
    plottype: 'Penthouse',
    buildingtype: 'Tower B',
    unittype: '4BR PH',
    numbedrooms: '4',
    numbathrooms: 4,
    numparkingslots: 2,
    netarea: 280.0,
    sellablearea: 350.5,
    baseprice: 9500000,
    cashprice: 8700000,
    maintenancepercent: 3.0,
    maintenancevalue: 28500,
    gas: 12000,
    parkingprice: 400000,
    finalprice: 9200000,
    discount: 300000,
    unitmodel: 'B1 PH',
    mirror: '',
    buildingnumber: 'B1',
    floor: '20',
    finishingspecs: 'Luxury Finished',
    internalarea: 240.0,
    coveredterraces: 40,
    uncoveredterraces: 70,
    bua: 350.5,
    psm: 27100,
    mainview: 'Panoramic',
    levels: 'Duplex PH',
    customer: 'Fatma Hassan',
    broker: 'Premium Sales',
    creationdate: '2025-01-20'
  },
  // Add 20+ more realistic mock units following the same structure...
  {
    unitcode: 'A2-105',
    city: 'New Cairo',
    project: 'Sun Capital',
    status: 'Available',
    plottype: 'Studio',
    buildingtype: 'Tower A',
    unittype: 'Studio',
    numbedrooms: '1',
    numbathrooms: 1,
    numparkingslots: 1,
    netarea: 65.3,
    sellablearea: 75.1,
    baseprice: 1800000,
    cashprice: 1650000,
    maintenancepercent: 2.0,
    maintenancevalue: 3600,
    gas: 3000,
    parkingprice: 100000,
    finalprice: 1800000,
    discount: 0,
    unitmodel: 'A2',
    mirror: '',
    buildingnumber: 'A2',
    floor: '1',
    finishingspecs: 'Core & Shell',
    internalarea: 60.3,
    coveredterraces: 5,
    uncoveredterraces: 10,
    bua: 75.1,
    psm: 23950,
    mainview: 'Street',
    levels: 'Single',
    customer: '',
    broker: '',
    creationdate: '2025-03-10'
  }
];
